### ISSUE TITLE
Can not run the demo , the namespace is lost.

### ISSUE THREAD

**Issue by adndyxu** [jsplumb-toolkit-demonstrations/vue3-flowchart-builder#1]
I'm a new user of jsplumb , I just clone this vue3 demo and run install , some error occurred:The package:@jsplumbtoolkit/* not found .
![image](https://user-images.githubusercontent.com/35793754/138015260-16e948e6-0f4d-4e03-b1d4-c7110f83a111.png)
Did the namespce @jsplumbtoolkit exists?Can anyone help upgrade the demo so I can run it?
Thx!

**Comment by cooper667** [comment]
You need to have access to the repository: https://docs.jsplumbtoolkit.com/toolkit/5.x/lib/npm-repository
